ALTER TABLE BOOKS ADD COLUMN GENRE_ID BIGINT;
UPDATE BOOKS b SET GENRE_ID = (SELECT g.ID FROM GENRES g WHERE g.NAME = b.GENRE);
ALTER TABLE BOOKS ALTER COLUMN GENRE_ID SET NOT NULL;
ALTER TABLE BOOKS ADD CONSTRAINT FK_BOOKS_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);
ALTER TABLE BOOKS DROP COLUMN GENRE;
CREATE INDEX IX_BOOKS_GENRE_ID ON BOOKS(GENRE_ID);
